### ISSUE TITLE
@authority component duplicates non-standard port, giving invalid signature

### ISSUE THREAD

**Issue by gsvarovsky** [dhensby/node-http-message-signatures#54]
The `extractComponent` function for `@authority` concatenates the URL `host` and `port` (if not a standard port), giving e.g. `localhost:56800:56800`.

It should be using the URL `hostname` instead.

Many thanks for this lib; I will submit a PR if I get the chance.

**Comment by dhensby** [comment]
this should be fixed in v1.0.0
